config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'species#index'
  resources :species
end

app/models/Species.rb
class Species < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  PER = 50

  def index
    @q = Species.page(params[:page]).per(PER).search(search_params)
    @species = @q.result(distinct: true)
  end

  def show
    @species = Species.find(params[:id])
  end

  def new
    @species = Species.new
  end

  def create
    @species = Species.new(species_params)
    if @species.save
      redirect_to @species, notice: '作成しました'
    else
      render :new
    end
  end

  def edit
    @species = Species.find(params[:id])
  end

  def update
    @species = Species.find(params[:id])
    if @species.update(species_params)
      redirect_to @species, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @species = Species.find(params[:id])
    @species.destroy!
    redirect_to species_path, notice: '削除しました'
  end

  def species_params
    params.require(:species).permit(
        :scientific_name, :japanese_name,
        :chinese_name, :korean_name,
        :english_name
    )
  end

  def search_params
    params.fetch(:q, {}).permit(:scientific_name_cont, :japanese_name_cont, :chinese_name_cont, :korean_name_cont, :english_name_cont)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aquryl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/species/_form.html.slim
ul
  - @species.errors.full_messages.each do |message|
    li = message

= bootstrap_form_for @species do |f|
  .row
    .col-md-8
      = f.text_field :scientific_name
  .row
    .col-md-4
      = f.text_field :japanese_name
    .col-md-4
      = f.text_field :english_name
  .row
    .col-md-4
      = f.text_field :chinese_name
    .col-md-4
      = f.text_field :korean_name
  .row
    .col-md-4
      = f.submit '保存', class: 'btn btn-success btn-block'
    .col-md-4
      = link_to '戻る', root_path, class: 'btn btn-secondary btn-block'

app/views/species/edit.html.slim
h1 情報編集
= render 'form'

app/views/species/index.html.slim
/ = react_component("App")
.container.p-4
  h1 Aquryl
  .card.p-3
    details
      summary 検索する
      = search_form_for(@q) do |f|
        .form-group
          = f.label :scientific_name_cont, '学名'
          = f.text_field :scientific_name_cont, class: 'form-control'
        .form-group
          = f.label :japanese_name_cont, '日本語名'
          = f.text_field :japanese_name_cont, class: 'form-control'
        .form-group
          = f.label :english_name_cont, '英語名'
          = f.text_field :english_name_cont, class: 'form-control'
        .form-group
          = f.label :chinese_name_cont, '中国語名'
          = f.text_field :chinese_name_cont, class: 'form-control'
        .form-group
          = f.label :korean_name_cont, '韓国語名'
          = f.text_field :korean_name_cont, class: 'form-control'
        = f.submit '検索', class: 'btn btn-primary'
        = link_to 'クリア', request.path, class: 'btn btn-secondary'

  - if @species.present?
    .table-responsive.mt-3
      = paginate @species
      table.table.table-striped
        thead
          tr
            th 学名
            th 日
            th 英
            th 中
            th 韓
            th
        tbody
          - @species.each do |item|
            tr
              td
                =link_to "#{item.scientific_name}", species_path(item)
              td
                =link_to "#{item.japanese_name}", species_path(item)
              td
                =link_to "#{item.english_name}", species_path(item)
              td
                =link_to "#{item.chinese_name}", species_path(item)
              td
                =link_to "#{item.korean_name}", species_path(item)
              td
                = link_to '編集', edit_species_path(item), class: "btn btn-success btn-xs"
                = link_to '削除', species_path(item), data: {:confirm => '本当によろしいですか?'}, :method => :delete, class: "btn btn-danger btn-xs"
    = paginate @species
    = link_to '新規作成', new_species_path, class: "btn btn-primary"
  - else
    p 種が存在しません。

app/views/species/new.html.slim
h1 新規作成
= render 'form'

app/views/species/show.html.slim
h1 #{@species.japanese_name}
.col-md-8
  dl
    dt 学名
    dd = @species.scientific_name
    dt 和名
    dd = @species.japanese_name
    dt 英名
    dd = @species.english_name
    dt 中名
    dd = @species.chinese_name
    dt 韓名
    dd = @species.korean_name
  = link_to '編集する', edit_species_path(@species), class: "btn btn-success btn-xs"
  = link_to '削除する', species_path(@species), data: {:confirm => '本当によろしいですか?'}, :method => :delete, class: "btn btn-danger btn-xs"
  br
  = link_to '戻る', root_path, class: 'btn btn-secondary btn-xs'